parameters:
  rust_version: nightly

jobs:
  - job: ${{ parameters.name }}
    displayName: Minimal versions
    strategy:
      matrix:
        Linux:
          vmImage: ubuntu-18.04
        Windows:
          vmImage: windows-latest
    pool:
      vmImage: $(vmImage)

    variables:
      RUST_BACKTRACE: full

    steps:
      - template: azure-install-rust.yml
        parameters:
          rust_version: ${{ parameters.rust_version }}

      - script: cargo update -Zminimal-versions
        displayName: cargo update -Zminimal-versions
        env:
          CI: "True"

      - script: cargo test --all-features
        displayName: cargo test --all-features
        env:
          CI: "True"
